# Generated by Django 4.2.2 on 2023-06-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=25, unique=True, verbose_name='이메일')),
                ('password', models.CharField(max_length=25, verbose_name='비밀번호')),
                ('nickname', models.CharField(blank=True, max_length=8, null=True, verbose_name='닉네임')),
                ('interest', models.CharField(choices=[('경제', 'economy'), ('it/과학', 'it'), ('날씨', 'weather'), ('생활/문화', 'culture'), ('세계', 'wrold')], max_length=20, verbose_name='관심분야')),
                ('profile_img', models.ImageField(blank=True, upload_to='profile/%Y/%m/', verbose_name='프로필 이미지')),
                ('is_admin', models.BooleanField(default=False, verbose_name='관리자')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
